import type { Player, Payment, ClubEvent } from "@/types";

export const players: Player[] = [
  { 
    id: '1', 
    firstName: 'John', 
    lastName: 'Doe', 
    dateOfBirth: new Date('2010-05-12'), 
    category: 'U15', 
    photoUrl: 'https://placehold.co/100x100.png',
    address: '123 Rue de Exemple',
    city: 'Paris',
    phone: '0123456789',
    guardianName: 'Richard Doe',
    guardianPhone: '0987654321',
    position: 'Attaquant',
    playerNumber: 10,
    email: 'john.doe@example.com',
    clubEntryDate: new Date('2020-09-01'),
  },
  { 
    id: '2', 
    firstName: 'Jane', 
    lastName: 'Smith', 
    dateOfBirth: new Date('2012-08-20'), 
    category: 'U13', 
    photoUrl: 'https://placehold.co/100x100.png',
    address: '456 Avenue de Test',
    city: 'Lyon',
    phone: '0234567891',
    guardianName: 'Laura Smith',
    guardianPhone: '0876543210',
    position: 'Défenseur',
    playerNumber: 4,
    email: 'jane.smith@example.com',
    clubEntryDate: new Date('2021-09-01'),
  },
  { 
    id: '3', 
    firstName: 'Mike', 
    lastName: 'Johnson', 
    dateOfBirth: new Date('1998-02-01'), 
    category: 'Senior', 
    photoUrl: 'https://placehold.co/100x100.png',
    address: '789 Boulevard de Démo',
    city: 'Marseille',
    phone: '0345678912',
    guardianName: 'N/A',
    guardianPhone: 'N/A',
    position: 'Milieu',
    playerNumber: 8,
    email: 'mike.johnson@example.com',
    clubEntryDate: new Date('2018-09-01'),
    clubExitDate: new Date('2023-06-30'),
  },
  { 
    id: '4', 
    firstName: 'Emily', 
    lastName: 'Brown', 
    dateOfBirth: new Date('2014-11-30'), 
    category: 'U11', 
    photoUrl: 'https://placehold.co/100x100.png',
    address: '101 Rue de Code',
    city: 'Lille',
    phone: '0456789123',
    guardianName: 'Paul Brown',
    guardianPhone: '0765432109',
    position: 'Gardien',
    playerNumber: 1,
    email: 'emily.brown@example.com',
    clubEntryDate: new Date('2022-09-01'),
  },
  { 
    id: '5', 
    firstName: 'Chris', 
    lastName: 'Davis', 
    dateOfBirth: new Date('2008-07-22'), 
    category: 'U17', 
    photoUrl: 'https://placehold.co/100x100.png',
    address: '212 Rue de Bogue',
    city: 'Toulouse',
    phone: '0567891234',
    guardianName: 'Sarah Davis',
    guardianPhone: '0654321098',
    position: 'Attaquant',
    playerNumber: 9,
    email: 'chris.davis@example.com',
    clubEntryDate: new Date('2019-09-01'),
  },
  { 
    id: '6', 
    firstName: 'Sarah', 
    lastName: 'Miller', 
    dateOfBirth: new Date('2016-01-15'), 
    category: 'U9', 
    photoUrl: 'https://placehold.co/100x100.png',
    address: '333 Chemin de Données',
    city: 'Nice',
    phone: '0678912345',
    guardianName: 'David Miller',
    guardianPhone: '0543210987',
    position: 'Milieu',
    playerNumber: 7,
    email: 'sarah.miller@example.com',
    clubEntryDate: new Date('2023-09-01'),
  },
];

export const payments: Payment[] = [
  { id: 'p1', playerId: '1', playerName: 'John Doe', amount: 250, date: new Date('2023-09-01'), status: 'Paid' },
  { id: 'p2', playerId: '2', playerName: 'Jane Smith', amount: 250, date: new Date('2023-09-05'), status: 'Paid' },
  { id: 'p3', playerId: '3', playerName: 'Mike Johnson', amount: 300, date: new Date('2023-09-10'), status: 'Pending' },
  { id: 'p4', playerId: '4', playerName: 'Emily Brown', amount: 200, date: new Date('2023-08-15'), status: 'Overdue' },
  { id: 'p5', playerId: '5', playerName: 'Chris Davis', amount: 250, date: new Date('2023-09-02'), status: 'Paid' },
];

export const clubEvents: ClubEvent[] = [
  { id: 'e1', title: 'Match vs. City Rovers', type: 'Match', date: new Date(new Date().setDate(new Date().getDate() + 3)) },
  { id: 'e2', title: 'Entraînement U15', type: 'Training', date: new Date(new Date().setDate(new Date().getDate() + 1)) },
  { id: 'e3', title: 'Entraînement équipe senior', type: 'Training', date: new Date(new Date().setDate(new Date().getDate() + 2)) },
  { id: 'e4', title: 'Tournoi U11', type: 'Match', date: new Date(new Date().setDate(new Date().getDate() + 10)) },
];
