
import type { Player, Payment, ClubEvent, Coach } from "@/types";

export const players: Player[] = [
  { 
    id: '1', 
    firstName: 'John', 
    lastName: 'Doe',
    gender: 'Homme',
    dateOfBirth: new Date('2010-05-12'), 
    category: 'U15', 
    photoUrl: 'https://placehold.co/100x100.png',
    address: '123 Rue de Exemple',
    city: 'Paris',
    phone: '0123456789',
    guardianName: 'Richard Doe',
    guardianPhone: '0987654321',
    position: 'Attaquant',
    playerNumber: 10,
    email: 'john.doe@example.com',
    clubEntryDate: new Date('2020-09-01'),
  },
  { 
    id: '2', 
    firstName: 'Jane', 
    lastName: 'Smith',
    gender: 'Femme',
    dateOfBirth: new Date('2012-08-20'), 
    category: 'U13', 
    photoUrl: 'https://placehold.co/100x100.png',
    address: '456 Avenue de Test',
    city: 'Lyon',
    phone: '0234567891',
    guardianName: 'Laura Smith',
    guardianPhone: '0876543210',
    position: 'Défenseur',
    playerNumber: 4,
    email: 'jane.smith@example.com',
    clubEntryDate: new Date('2021-09-01'),
  },
  { 
    id: '3', 
    firstName: 'Mike', 
    lastName: 'Johnson',
    gender: 'Homme',
    dateOfBirth: new Date('1998-02-01'), 
    category: 'Senior', 
    photoUrl: 'https://placehold.co/100x100.png',
    address: '789 Boulevard de Démo',
    city: 'Marseille',
    phone: '0345678912',
    guardianName: 'N/A',
    guardianPhone: 'N/A',
    position: 'Milieu',
    playerNumber: 8,
    email: 'mike.johnson@example.com',
    clubEntryDate: new Date('2018-09-01'),
    clubExitDate: new Date('2023-06-30'),
  },
  { 
    id: '4', 
    firstName: 'Emily', 
    lastName: 'Brown',
    gender: 'Femme',
    dateOfBirth: new Date('2014-11-30'), 
    category: 'U11', 
    photoUrl: 'https://placehold.co/100x100.png',
    address: '101 Rue de Code',
    city: 'Lille',
    phone: '0456789123',
    guardianName: 'Paul Brown',
    guardianPhone: '0765432109',
    position: 'Gardien',
    playerNumber: 1,
    email: 'emily.brown@example.com',
    clubEntryDate: new Date('2022-09-01'),
  },
  { 
    id: '5', 
    firstName: 'Chris', 
    lastName: 'Davis',
    gender: 'Homme',
    dateOfBirth: new Date('2008-07-22'), 
    category: 'U17', 
    photoUrl: 'https://placehold.co/100x100.png',
    address: '212 Rue de Bogue',
    city: 'Toulouse',
    phone: '0567891234',
    guardianName: 'Sarah Davis',
    guardianPhone: '0654321098',
    position: 'Attaquant',
    playerNumber: 9,
    email: 'chris.davis@example.com',
    clubEntryDate: new Date('2019-09-01'),
  },
  { 
    id: '6', 
    firstName: 'Sarah', 
    lastName: 'Miller',
    gender: 'Femme',
    dateOfBirth: new Date('2016-01-15'), 
    category: 'U9', 
    photoUrl: 'https://placehold.co/100x100.png',
    address: '333 Chemin de Données',
    city: 'Nice',
    phone: '0678912345',
    guardianName: 'David Miller',
    guardianPhone: '0543210987',
    position: 'Milieu',
    playerNumber: 7,
    email: 'sarah.miller@example.com',
    clubEntryDate: new Date('2023-09-01'),
  },
  {
    id: '7',
    firstName: 'Aya',
    lastName: 'Boukhari',
    gender: 'Femme',
    dateOfBirth: new Date('2007-03-25'),
    category: 'U17',
    photoUrl: 'https://placehold.co/100x100.png',
    address: '111 Rue Nouvelle',
    city: 'Casablanca',
    phone: '0611223344',
    guardianName: 'Samir Boukhari',
    guardianPhone: '0655667788',
    position: 'Milieu offensif',
    playerNumber: 22,
    email: 'aya.boukhari@example.com',
    clubEntryDate: new Date('2022-09-01'),
  },
];

export const payments: Payment[] = [
  { id: 'p1', playerId: '1', playerName: 'John Doe', totalAmount: 300, advance: 300, remaining: 0, date: new Date('2023-09-01'), status: 'Paid' },
  { id: 'p2', playerId: '2', playerName: 'Jane Smith', totalAmount: 300, advance: 300, remaining: 0, date: new Date('2023-09-05'), status: 'Paid' },
  { id: 'p3', playerId: '3', playerName: 'Mike Johnson', totalAmount: 300, advance: 150, remaining: 150, date: new Date('2023-09-10'), status: 'Pending' },
  { id: 'p4', playerId: '4', playerName: 'Emily Brown', totalAmount: 300, advance: 0, remaining: 300, date: new Date('2023-08-15'), status: 'Overdue' },
  { id: 'p5', playerId: '5', playerName: 'Chris Davis', totalAmount: 300, advance: 300, remaining: 0, date: new Date('2023-09-02'), status: 'Paid' },
];

export const clubEvents: ClubEvent[] = [
  { id: 'e1', title: 'Match vs. City Rovers', type: 'Match', date: new Date(new Date().setDate(new Date().getDate() + 3)) },
  { id: 'e2', title: 'Entraînement U15', type: 'Training', date: new Date(new Date().setDate(new Date().getDate() + 1)) },
  { id: 'e3', title: 'Entraînement équipe senior', type: 'Training', date: new Date(new Date().setDate(new Date().getDate() + 2)) },
  { id: 'e4', title: 'Tournoi U11', type: 'Match', date: new Date(new Date().setDate(new Date().getDate() + 10)) },
];

export const coaches: Coach[] = [
  {
    id: 'c1',
    firstName: 'Didier',
    lastName: 'Deschamps',
    email: 'didier.d@example.com',
    phone: '0611223344',
    specialty: 'Entraîneur principal (Senior)',
    photoUrl: 'https://placehold.co/100x100.png',
    gender: 'Homme',
    country: 'France',
    city: 'Bayonne',
    dateOfBirth: new Date('1968-10-15'),
  },
  {
    id: 'c2',
    firstName: 'Zinedine',
    lastName: 'Zidane',
    email: 'zizou@example.com',
    phone: '0622334455',
    specialty: 'Entraîneur adjoint (Technique)',
    photoUrl: 'https://placehold.co/100x100.png',
    gender: 'Homme',
    country: 'France',
    city: 'Marseille',
    dateOfBirth: new Date('1972-06-23'),
  },
  {
    id: 'c3',
    firstName: 'Hervé',
    lastName: 'Renard',
    email: 'herve.r@example.com',
    phone: '0633445566',
    specialty: 'Entraîneur (U17 & U19)',
    photoUrl: 'https://placehold.co/100x100.png',
    gender: 'Homme',
    country: 'France',
    city: 'Aix-les-Bains',
    dateOfBirth: new Date('1968-09-30'),
  },
  {
    id: 'c4',
    firstName: 'Corinne',
    lastName: 'Diacre',
    email: 'corinne.d@example.com',
    phone: '0644556677',
    specialty: 'Entraîneur (Équipes féminines)',
    photoUrl: 'https://placehold.co/100x100.png',
    gender: 'Femme',
    country: 'France',
    city: 'Croix',
    dateOfBirth: new Date('1974-08-04'),
  }
];
