
import type { Player, Payment, ClubEvent, Coach, StatEvent } from "@/types";

export const players: Player[] = [
  { 
    id: '1', 
    firstName: 'John', 
    lastName: 'Doe',
    gender: 'Homme',
    dateOfBirth: new Date('2010-05-12'), 
    category: 'U15', 
    photoUrl: 'https://placehold.co/100x100.png',
    address: '123 Rue de Exemple',
    city: 'Paris',
    country: 'France',
    phone: '0123456789',
    guardianName: 'Richard Doe',
    guardianPhone: '0987654321',
    position: 'Attaquant',
    playerNumber: 10,
    email: 'john.doe@example.com',
    clubEntryDate: new Date('2020-09-01'),
  },
  { 
    id: '2', 
    firstName: 'Jane', 
    lastName: 'Smith',
    gender: 'Femme',
    dateOfBirth: new Date('2012-08-20'), 
    category: 'U13', 
    photoUrl: 'https://placehold.co/100x100.png',
    address: '456 Avenue de Test',
    city: 'Lyon',
    country: 'France',
    phone: '0234567891',
    guardianName: 'Laura Smith',
    guardianPhone: '0876543210',
    position: 'Défenseur',
    playerNumber: 4,
    email: 'jane.smith@example.com',
    clubEntryDate: new Date('2021-09-01'),
  },
  { 
    id: '3', 
    firstName: 'Mike', 
    lastName: 'Johnson',
    gender: 'Homme',
    dateOfBirth: new Date('1998-02-01'), 
    category: 'Senior', 
    photoUrl: 'https://placehold.co/100x100.png',
    address: '789 Boulevard de Démo',
    city: 'Marseille',
    country: 'France',
    phone: '0345678912',
    guardianName: 'N/A',
    guardianPhone: 'N/A',
    position: 'Milieu',
    playerNumber: 8,
    email: 'mike.johnson@example.com',
    clubEntryDate: new Date('2018-09-01'),
    clubExitDate: new Date('2023-06-30'),
  },
  { 
    id: '4', 
    firstName: 'Emily', 
    lastName: 'Brown',
    gender: 'Femme',
    dateOfBirth: new Date('2014-11-30'), 
    category: 'U11', 
    photoUrl: 'https://placehold.co/100x100.png',
    address: '101 Rue de Code',
    city: 'Lille',
    country: 'France',
    phone: '0456789123',
    guardianName: 'Paul Brown',
    guardianPhone: '0765432109',
    position: 'Gardien',
    playerNumber: 1,
    email: 'emily.brown@example.com',
    clubEntryDate: new Date('2022-09-01'),
  },
  { 
    id: '5', 
    firstName: 'Chris', 
    lastName: 'Davis',
    gender: 'Homme',
    dateOfBirth: new Date('2008-07-22'), 
    category: 'U17', 
    photoUrl: 'https://placehold.co/100x100.png',
    address: '212 Rue de Bogue',
    city: 'Toulouse',
    country: 'France',
    phone: '0567891234',
    guardianName: 'Sarah Davis',
    guardianPhone: '0654321098',
    position: 'Attaquant',
    playerNumber: 9,
    email: 'chris.davis@example.com',
    clubEntryDate: new Date('2019-09-01'),
  },
  { 
    id: '6', 
    firstName: 'Sarah', 
    lastName: 'Miller',
    gender: 'Femme',
    dateOfBirth: new Date('2016-01-15'), 
    category: 'U9', 
    photoUrl: 'https://placehold.co/100x100.png',
    address: '333 Chemin de Données',
    city: 'Nice',
    country: 'France',
    phone: '0678912345',
    guardianName: 'David Miller',
    guardianPhone: '0543210987',
    position: 'Milieu',
    playerNumber: 7,
    email: 'sarah.miller@example.com',
    clubEntryDate: new Date('2023-09-01'),
  },
  {
    id: '7',
    firstName: 'Aya',
    lastName: 'Boukhari',
    gender: 'Femme',
    dateOfBirth: new Date('2007-03-25'),
    category: 'U17',
    photoUrl: 'https://placehold.co/100x100.png',
    address: '111 Rue Nouvelle',
    city: 'Casablanca',
    country: 'Maroc',
    phone: '0611223344',
    guardianName: 'Samir Boukhari',
    guardianPhone: '0655667788',
    position: 'Milieu offensif',
    playerNumber: 22,
    email: 'aya.boukhari@example.com',
    clubEntryDate: new Date('2022-09-01'),
  },
];

export const payments: Payment[] = [
  { id: 'p1', memberId: '1', memberName: 'John Doe', memberType: 'player', totalAmount: 300, advance: 300, remaining: 0, date: new Date('2023-09-01'), status: 'Paid' },
  { id: 'p2', memberId: '2', memberName: 'Jane Smith', memberType: 'player', totalAmount: 300, advance: 300, remaining: 0, date: new Date('2023-09-05'), status: 'Paid' },
  { id: 'p3', memberId: '3', memberName: 'Mike Johnson', memberType: 'player', totalAmount: 300, advance: 150, remaining: 150, date: new Date('2023-09-10'), status: 'Pending' },
  { id: 'p4', memberId: '4', memberName: 'Emily Brown', memberType: 'player', totalAmount: 300, advance: 0, remaining: 300, date: new Date('2023-08-15'), status: 'Overdue' },
  { id: 'p5', memberId: '5', memberName: 'Chris Davis', memberType: 'player', totalAmount: 300, advance: 300, remaining: 0, date: new Date('2023-09-02'), status: 'Paid' },
  { id: 'p6', memberId: 'c1', memberName: 'Didier Deschamps', memberType: 'coach', totalAmount: 500, advance: 500, remaining: 0, date: new Date('2023-10-01'), status: 'Paid' },
  { id: 'p7', memberId: 'c2', memberName: 'Zinedine Zidane', memberType: 'coach', totalAmount: 500, advance: 250, remaining: 250, date: new Date('2023-10-05'), status: 'Pending' },
];

export const clubEvents: ClubEvent[] = [
  { 
    id: 'e1', 
    title: 'Match de championnat', 
    type: 'Match', 
    opponent: 'City Rovers',
    date: new Date(new Date().setDate(new Date().getDate() + 3)),
    time: '15:00',
    location: 'Stade Municipal',
    category: 'Senior',
    description: 'Match de championnat important. Convocation à 13:30.'
  },
  { 
    id: 'e2', 
    title: 'Entraînement physique', 
    type: 'Entraînement', 
    date: new Date(new Date().setDate(new Date().getDate() + 1)),
    time: '18:30',
    location: 'Terrain annexe',
    category: 'U15',
    description: 'Séance axée sur l\'endurance et la vitesse.'
  },
  { 
    id: 'e3', 
    title: 'Réunion des éducateurs', 
    type: 'Réunion', 
    date: new Date(new Date().setDate(new Date().getDate() + 2)),
    time: '19:00',
    location: 'Club-house',
    category: 'Éducateurs',
    description: 'Ordre du jour : planification du prochain cycle et organisation du tournoi.'
  },
  { 
    id: 'e4', 
    title: 'Tournoi U11', 
    type: 'Événement', 
    date: new Date(new Date().setDate(new Date().getDate() + 10)),
    time: '09:00',
    location: 'Complexe sportif régional',
    category: 'U11',
    description: 'Tournoi régional sur toute la journée. Prévoir pique-nique.'
  },
  { 
    id: 'e5', 
    title: 'Entraînement tactique', 
    type: 'Entraînement', 
    date: new Date(),
    time: '18:00',
    location: 'Stade Principal',
    category: 'Senior',
    description: 'Mise en place pour le match du week-end.'
  },
   { 
    id: 'e6', 
    title: 'Soirée du club', 
    type: 'Événement', 
    date: new Date(),
    time: '20:00',
    location: 'Salle des fêtes',
    category: 'Tous les membres',
    description: 'Repas annuel du club pour fêter la fin de saison.'
  },
];

export const coaches: Coach[] = [
  {
    id: 'c1',
    firstName: 'Didier',
    lastName: 'Deschamps',
    email: 'didier.d@example.com',
    phone: '0611223344',
    specialty: 'Entraîneur principal (Senior)',
    photoUrl: 'https://placehold.co/100x100.png',
    gender: 'Homme',
    country: 'France',
    city: 'Bayonne',
    age: 55,
    clubEntryDate: new Date('2018-08-01'),
  },
  {
    id: 'c2',
    firstName: 'Zinedine',
    lastName: 'Zidane',
    email: 'zizou@example.com',
    phone: '0622334455',
    specialty: 'Entraîneur adjoint',
    photoUrl: 'https://placehold.co/100x100.png',
    gender: 'Homme',
    country: 'France',
    city: 'Marseille',
    age: 52,
    clubEntryDate: new Date('2021-07-01'),
    clubExitDate: new Date('2023-06-30'),
  },
  {
    id: 'c3',
    firstName: 'Hervé',
    lastName: 'Renard',
    email: 'herve.r@example.com',
    phone: '0633445566',
    specialty: 'Entraîneur (U17)',
    photoUrl: 'https://placehold.co/100x100.png',
    gender: 'Homme',
    country: 'France',
    city: 'Aix-les-Bains',
    age: 55,
    clubEntryDate: new Date('2022-01-15'),
  },
  {
    id: 'c4',
    firstName: 'Corinne',
    lastName: 'Diacre',
    email: 'corinne.d@example.com',
    phone: '0644556677',
    specialty: 'Entraîneur (Équipes féminines)',
    photoUrl: 'https://placehold.co/100x100.png',
    gender: 'Femme',
    country: 'France',
    city: 'Croix',
    age: 50,
    clubEntryDate: new Date('2020-09-01'),
  }
];
